# Generated by Django 4.2.9 on 2024-03-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_alter_user_nickname_alter_user_public_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="public_key",
            field=models.CharField(max_length=1000, verbose_name="公钥"),
        ),
    ]
