# Generated by Django 4.2.9 on 2024-03-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(max_length=25, verbose_name="昵称"),
        ),
        migrations.AlterField(
            model_name="user",
            name="public_key",
            field=models.CharField(max_length=18, verbose_name="公钥"),
        ),
    ]
